---
hostname: rt-vyos-1

bgp:
  bgp_as: 65003
  neighbors:
    - peer_as: 65002
      peer_ip: 10.0.0.2
    - peer_as: 65001
      peer_ip: 10.0.0.3

interfaces:
  "eth1":
    ip: 10.0.0.1/29
    description: "Interco_with_other_routers"

loopback:
  "dum1":
    ip: 100.64.1.3/32
    description: "BGP_Loopback"
  "dum2":
    ip: 3.3.3.3/32
    description: "BGP_Loopback"
